#!/usr/bin/env python3
"""Run Brainstack memory-kernel release checks as one public-safe gate."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RELEASE_CLAIM_CONTRACT = ROOT / ".planning" / "release" / "RELEASE-CLAIM-CONTRACT.json"
DEFAULT_RELEASE_NOTES = ROOT / ".planning" / "release" / "RELEASE-NOTES.md"
UNBREAKABLE_TARGET = (
    "MINDE HELYZHETBEN BÁRMILYEN ESETBEN AKÁRHOGY KOMIBNÁLVA BÁRMILYEN "
    "HASZNÁLAT KÖZBEN NEM TÖRHET EL SEMMILYEN ESETBEN SEM SOHA SEHHOGY!"
)
REQUIRED_OPERATION_CLASSES = {
    "inputs",
    "state_transitions",
    "error_modes",
    "conflicts",
    "provider_runtime_failures",
    "replay_idempotency",
    "isolation",
    "contamination",
    "budget_pressure",
    "source_runtime_parity",
    "release_note_truthfulness",
    "arbitrary_combinations",
}
GATE_EVASION_PATTERNS = {
    "scope_shrink",
    "definition_drift",
    "evidence_laundering",
    "silent_downgrade",
    "degraded_success",
    "manual_override",
    "release_note_softening",
    "side_issue_parking",
    "mirror_only_fix",
    "test_only_compliance",
    "metric_cherry_pick",
    "sota_claim_split",
    "fail_closed_abuse",
    "temporary_fallback_as_final",
}
RELEASE_NOTE_FORBIDDEN_PATTERNS = {
    "internal_qa_noise": re.compile(
        r"\b(ruff|pytest|docker rebuild|release checklist|installer doctor|smoke test)\b",
        re.IGNORECASE,
    ),
    "negative_self_disqualification": re.compile(
        r"\b(does not claim|not claim|not product[- ]complete|boundary:|not complete|not ready)\b",
        re.IGNORECASE,
    ),
    "non_maintainer_attribution": re.compile(
        r"\b(co-authored-by|authored by|generated by|automation authored|machine authored)\b",
        re.IGNORECASE,
    ),
}
SUPERIORITY_PATTERN = re.compile(
    r"\b(SOTA|superior|superiority|best|world[- ]class|state[- ]of[- ]the[- ]art)\b",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class CheckResult:
    name: str
    status: str
    command: list[str]
    returncode: int
    summary: dict[str, Any]


def _run(command: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _json_from_stdout(stdout: str) -> dict[str, Any]:
    return json.loads(stdout.strip() or "{}")


def _status(passed: bool) -> str:
    return "pass" if passed else "fail"


def _as_bool(value: Any) -> bool:
    return value is True


def _as_string_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, str) and item.strip()]


def _check_release_claim_contract(
    contract_path: Path = DEFAULT_RELEASE_CLAIM_CONTRACT,
    notes_path: Path = DEFAULT_RELEASE_NOTES,
) -> CheckResult:
    issues: list[dict[str, Any]] = []
    command = ["release claim contract", str(contract_path), str(notes_path)]
    contract: dict[str, Any] = {}
    notes_text = ""

    if not contract_path.exists():
        issues.append({"code": "missing_release_claim_contract", "path": str(contract_path)})
    else:
        try:
            contract = _load_json(contract_path)
        except (OSError, json.JSONDecodeError) as exc:
            issues.append(
                {
                    "code": "invalid_release_claim_contract_json",
                    "path": str(contract_path),
                    "error": str(exc),
                }
            )

    if not notes_path.exists():
        issues.append({"code": "missing_release_notes", "path": str(notes_path)})
    else:
        try:
            notes_text = notes_path.read_text(encoding="utf-8")
        except OSError as exc:
            issues.append({"code": "unreadable_release_notes", "path": str(notes_path), "error": str(exc)})

    if contract:
        if contract.get("schema") != "brainstack.release_claim_contract.v1":
            issues.append({"code": "unsupported_contract_schema", "value": contract.get("schema")})
        if contract.get("stable_release_decision") != "allowed":
            issues.append(
                {
                    "code": "stable_release_decision_not_allowed",
                    "value": contract.get("stable_release_decision"),
                }
            )
        if contract.get("unbreakable_target") != UNBREAKABLE_TARGET:
            issues.append({"code": "unbreakable_target_missing_or_mutated"})
        if not isinstance(contract.get("claim_summary"), str) or not contract["claim_summary"].strip():
            issues.append({"code": "claim_summary_missing"})

        proof = contract.get("unbreakable_operation_proof")
        if not isinstance(proof, dict):
            issues.append({"code": "unbreakable_operation_proof_missing"})
            proof = {}
        if proof.get("status") != "pass":
            issues.append({"code": "unbreakable_operation_proof_not_pass", "value": proof.get("status")})
        classes = set(_as_string_list(proof.get("operating_space_classes")))
        missing_classes = sorted(REQUIRED_OPERATION_CLASSES - classes)
        if missing_classes:
            issues.append({"code": "operating_space_classes_missing", "missing": missing_classes})
        required_true = {
            "arbitrary_combination_coverage",
            "structural_forbidden_state_analysis",
            "no_permanent_disable",
            "no_regression",
            "no_feature_removal",
            "no_capability_shutdown",
            "no_dumbing_down",
            "no_permanent_degraded_mode",
        }
        for key in sorted(required_true):
            if not _as_bool(proof.get(key)):
                issues.append({"code": "unbreakable_proof_required_flag_not_true", "field": key})
        if not _as_string_list(proof.get("structurally_impossible_states")):
            issues.append({"code": "structurally_impossible_states_missing"})
        if not _as_string_list(proof.get("temporary_error_guards")):
            issues.append({"code": "temporary_error_guards_missing"})

        gate_evasion = contract.get("gate_evasion")
        if not isinstance(gate_evasion, dict):
            issues.append({"code": "gate_evasion_section_missing"})
            gate_evasion = {}
        if gate_evasion.get("status") != "pass":
            issues.append({"code": "gate_evasion_status_not_pass", "value": gate_evasion.get("status")})
        for pattern in sorted(GATE_EVASION_PATTERNS):
            if gate_evasion.get(pattern) is not False:
                issues.append({"code": "gate_evasion_pattern_not_rejected", "pattern": pattern})

        immutable = contract.get("immutable_principles")
        if not isinstance(immutable, dict):
            issues.append({"code": "immutable_principles_section_missing"})
            immutable = {}
        if immutable.get("status") != "pass":
            issues.append({"code": "immutable_principles_status_not_pass", "value": immutable.get("status")})
        if immutable.get("violations") not in ([], None):
            issues.append({"code": "immutable_principles_violations_present"})

        sota_gate_required = contract.get("sota_gate_required")
        if not isinstance(sota_gate_required, bool):
            issues.append({"code": "sota_gate_requirement_missing"})
            sota_gate_required = False
        if sota_gate_required:
            sota_gate = contract.get("sota_gate")
            if not isinstance(sota_gate, dict) or sota_gate.get("status") != "pass":
                issues.append({"code": "sota_gate_required_but_not_pass"})

        evidence = contract.get("evidence")
        if not isinstance(evidence, list) or not evidence:
            issues.append({"code": "evidence_missing"})
        else:
            passing_evidence_count = 0
            for index, item in enumerate(evidence):
                if not isinstance(item, dict):
                    issues.append({"code": "evidence_item_invalid", "index": index})
                    continue
                if item.get("status") == "pass":
                    passing_evidence_count += 1
                for field in ("name", "kind", "summary"):
                    if not isinstance(item.get(field), str) or not item[field].strip():
                        issues.append({"code": "evidence_item_field_missing", "index": index, "field": field})
            if passing_evidence_count < 3:
                issues.append({"code": "evidence_too_weak", "passing_evidence_count": passing_evidence_count})

    superiority_claim_in_notes = bool(notes_text and SUPERIORITY_PATTERN.search(notes_text))
    if notes_text:
        for name, pattern in RELEASE_NOTE_FORBIDDEN_PATTERNS.items():
            if pattern.search(notes_text):
                issues.append({"code": "release_notes_forbidden_pattern", "pattern": name})
        for term in _private_payload_terms():
            if term in notes_text:
                issues.append(
                    {
                        "code": "release_notes_private_denylist_term",
                        "term_hash": hashlib.sha256(term.encode("utf-8")).hexdigest()[:16],
                    }
                )
        if superiority_claim_in_notes:
            sota_gate = contract.get("sota_gate") if contract else {}
            if not isinstance(sota_gate, dict) or sota_gate.get("status") != "pass":
                issues.append({"code": "superiority_claim_without_sota_gate"})

    passed = not issues
    return CheckResult(
        name="release_claim_contract",
        status=_status(passed),
        command=command,
        returncode=0 if passed else 1,
        summary={
            "contract_path": str(contract_path),
            "release_notes_path": str(notes_path),
            "issue_count": len(issues),
            "issues": issues[:40],
            "required_operation_class_count": len(REQUIRED_OPERATION_CLASSES),
            "gate_evasion_pattern_count": len(GATE_EVASION_PATTERNS),
            "superiority_claim_in_notes": superiority_claim_in_notes,
        },
    )


def _check_tier2_unbreakable_operation(tmp: Path) -> CheckResult:
    out = tmp / "tier2_unbreakable_operation_audit.json"
    phase_dir = tmp / "tier2_unbreakable_artifacts"
    command = [
        sys.executable,
        "scripts/audit_tier2_unbreakable_operation.py",
        "--phase-dir",
        str(phase_dir),
        "--artifact-prefix",
        "249",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("issue_count") == 0
        and all(value is True for value in (data.get("proof_families") or {}).values())
        and not any(
            value
            for key, value in (data.get("critical_counters") or {}).items()
            if key != "canonical_event_count"
        )
    )
    return CheckResult(
        name="tier2_unbreakable_operation",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "issue_count": data.get("issue_count"),
            "issues": (data.get("issues") or [])[:20],
            "critical_counters": data.get("critical_counters"),
            "proof_families": data.get("proof_families"),
            "canonical_event_count": data.get("canonical_event_count"),
        },
    )


def _check_phase249_ralph_gate(tmp: Path) -> CheckResult:
    out = tmp / "phase249_ralph_gate.json"
    command = [
        sys.executable,
        "scripts/check_phase249_ralph_gate.py",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = proc.returncode == 0 and data.get("status") == "pass" and data.get("issue_count") == 0
    return CheckResult(
        name="phase249_ralph_gate",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "issue_count": data.get("issue_count"),
            "issues": (data.get("issues") or [])[:20],
            "open_item_count": len(data.get("open_items") or []),
            "blocked_item_count": len(data.get("blocked_items") or []),
            "next_action": data.get("next_action"),
        },
    )


def _check_public_corpus(tmp: Path) -> CheckResult:
    out = tmp / "public_corpus_audit.json"
    command = [sys.executable, "scripts/audit_public_memory_kernel_corpus.py", "--out", str(out)]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = proc.returncode == 0 and data.get("status") == "pass" and not data.get("issues")
    return CheckResult(
        name="public_memory_kernel_corpus",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "scenario_count": data.get("scenario_count"),
            "negative_count": data.get("negative_count"),
            "leak_findings_count": len(data.get("leak_findings") or []),
            "issue_count": len(data.get("issues") or []),
        },
    )


def _check_evidence_trace(tmp: Path) -> CheckResult:
    out = tmp / "evidence_trace_audit.json"
    command = [sys.executable, "scripts/audit_evidence_trace_standard.py", "--out", str(out)]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = proc.returncode == 0 and data.get("status") == "pass" and data.get("issue_count") == 0
    return CheckResult(
        name="evidence_trace_standard",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "scenario_count": data.get("scenario_count"),
            "complete_trace_count": data.get("complete_trace_count"),
            "proof_chain_count": data.get("proof_chain_count"),
            "unknown_reason_code_count": data.get("unknown_reason_code_count"),
            "raw_text_issue_count": data.get("raw_text_issue_count"),
            "issue_count": data.get("issue_count"),
        },
    )


def _check_packet_budget(tmp: Path) -> CheckResult:
    out = tmp / "packet_budget_live_shadow.json"
    command = [
        sys.executable,
        "scripts/measure_packet_budget_live_shadow_telemetry.py",
        "--sample-count",
        "24",
        "--budget-max-candidate-tokens",
        "120",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = (
        proc.returncode == 0
        and data.get("scenario_count", 0) >= 20
        and data.get("distinct_scenario_family_count", 0) >= 6
        and data.get("output_changed_in_shadow") is False
        and data.get("protected_truth_drop_attempts") == 0
        and bool(data.get("activation_verdict"))
    )
    return CheckResult(
        name="packet_budget_live_shadow",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "scenario_count": data.get("scenario_count"),
            "distinct_scenario_family_count": data.get("distinct_scenario_family_count"),
            "estimated_delta_percent": data.get("estimated_delta_percent"),
            "protected_truth_drop_attempts": data.get("protected_truth_drop_attempts"),
            "output_changed_in_shadow": data.get("output_changed_in_shadow"),
            "fusion_signal_count": data.get("fusion_signal_count"),
            "retrieval_fusion_next_phase_required": data.get("retrieval_fusion_next_phase_required"),
            "activation_verdict": data.get("activation_verdict"),
        },
    )


def _check_active_packet_budget(tmp: Path) -> CheckResult:
    out = tmp / "packet_budget_active_rollout.json"
    command = [
        sys.executable,
        "scripts/measure_packet_budget_active_rollout.py",
        "--sample-count",
        "24",
        "--budget-max-candidate-tokens",
        "120",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = (
        proc.returncode == 0
        and data.get("active_budget_enabled_for_supported_paths") is True
        and data.get("protected_truth_drop_attempts") == 0
        and data.get("budget_decision_trace_present") is True
        and data.get("budget_reason_code_registry_pass") is True
        and data.get("raw_text_in_budget_trace") is False
        and data.get("unsupported_path_fail_closed_count") == 1
    )
    return CheckResult(
        name="packet_budget_active_rollout",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "active_budget_enabled_for_supported_paths": data.get(
                "active_budget_enabled_for_supported_paths"
            ),
            "scenario_count": data.get("scenario_count"),
            "distinct_scenario_family_count": data.get("distinct_scenario_family_count"),
            "candidate_token_delta_percent": data.get("candidate_token_delta_percent"),
            "packet_build_latency_overhead_ms_p95": data.get(
                "packet_build_latency_overhead_ms_p95"
            ),
            "protected_truth_drop_attempts": data.get("protected_truth_drop_attempts"),
            "budget_reason_code_registry_pass": data.get("budget_reason_code_registry_pass"),
            "raw_text_in_budget_trace": data.get("raw_text_in_budget_trace"),
            "unsupported_path_fail_closed_count": data.get("unsupported_path_fail_closed_count"),
        },
    )


def _check_packet_budget_soak(tmp: Path) -> CheckResult:
    out = tmp / "packet_budget_soak.json"
    command = [
        sys.executable,
        "scripts/run_packet_budget_soak.py",
        "--sample-count",
        "100",
        "--budget-max-candidate-tokens",
        "120",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("scenario_count", 0) >= 100
        and data.get("scenario_family_count", 0) >= 10
        and data.get("protected_truth_drop_attempts") == 0
        and data.get("selected_evidence_fingerprint_mismatch_count") == 0
        and data.get("trace_complete_count") == data.get("scenario_count")
        and data.get("soak_artifact_leak_findings") == 0
        and data.get("failure_bundle_count") == 0
        and data.get("retrieval_fusion_next_phase_required") is False
    )
    return CheckResult(
        name="packet_budget_soak",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "scenario_count": data.get("scenario_count"),
            "scenario_family_count": data.get("scenario_family_count"),
            "candidate_token_delta_percent": data.get("candidate_token_delta_percent"),
            "protected_truth_drop_attempts": data.get("protected_truth_drop_attempts"),
            "selected_evidence_fingerprint_mismatch_count": data.get(
                "selected_evidence_fingerprint_mismatch_count"
            ),
            "trace_complete_count": data.get("trace_complete_count"),
            "soak_artifact_leak_findings": data.get("soak_artifact_leak_findings"),
            "failure_bundle_count": data.get("failure_bundle_count"),
            "retrieval_fusion_next_phase_required": data.get(
                "retrieval_fusion_next_phase_required"
            ),
        },
    )


def _check_write_path(tmp: Path) -> CheckResult:
    out = tmp / "write_path_closure_audit.json"
    command = [sys.executable, "scripts/brainstack_write_path_closure_audit.py", "--json-out", str(out)]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = proc.returncode == 0 and data.get("hard_failure_count") == 0
    return CheckResult(
        name="write_path_closure",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "callsite_count": data.get("callsite_count"),
            "hard_failure_count": data.get("hard_failure_count"),
            "by_class": data.get("by_class", {}),
        },
    )


def _check_graph_conflict_lifecycle(tmp: Path) -> CheckResult:
    out = tmp / "graph_conflict_lifecycle_audit.json"
    command = [sys.executable, "scripts/audit_graph_conflict_lifecycle.py", "--out", str(out)]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("issue_count") == 0
        and data.get("release_blocked_before_resolution") is True
        and data.get("open_conflict_count_after_resolution") == 0
        and data.get("resolution_ledger_count") == 1
    )
    return CheckResult(
        name="graph_conflict_lifecycle",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "issue_count": data.get("issue_count"),
            "release_blocked_before_resolution": data.get("release_blocked_before_resolution"),
            "open_conflict_count_after_resolution": data.get("open_conflict_count_after_resolution"),
            "resolution_ledger_count": data.get("resolution_ledger_count"),
        },
    )


def _check_public_fixtures() -> CheckResult:
    command = [sys.executable, "scripts/run_public_memory_kernel_fixtures.py", "--contract-only"]
    proc = _run(command)
    data = _json_from_stdout(proc.stdout) if proc.stdout.strip().startswith("{") else {}
    passed = proc.returncode == 0 and data.get("negative") == "pass" and data.get("run") == "pass"
    return CheckResult(
        name="public_fixture_runner",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={"negative": data.get("negative"), "run": data.get("run")},
    )


def _tracked_files() -> list[str]:
    proc = _run(["git", "ls-files"])
    if proc.returncode != 0:
        return []
    return [line.strip() for line in proc.stdout.splitlines() if line.strip()]


def _private_payload_terms() -> list[str]:
    denylist_path = ROOT / ".planning" / "private_payload_denylist.txt"
    if not denylist_path.exists():
        return []
    terms: list[str] = []
    for raw in denylist_path.read_text(encoding="utf-8").splitlines():
        term = raw.strip()
        if not term or term.startswith("#"):
            continue
        terms.append(term)
    return terms


def _check_public_payload_leaks() -> CheckResult:
    local_terms = _private_payload_terms()
    platform_id_pattern = re.compile(
        r"(?:user_id|channel_id|thread_id|server_id|guild_id|principal|telegram|discord)[^\\n]{0,80}\\b\\d{12,}\\b",
        re.IGNORECASE,
    )
    token_shape_pattern = re.compile(r"\\b[A-Za-z0-9_-]{20,}\\.[A-Za-z0-9_-]{6,}\\.[A-Za-z0-9_-]{20,}\\b")
    findings: list[dict[str, Any]] = []
    for relative in _tracked_files():
        path = ROOT / relative
        if not path.is_file() or "__pycache__" in path.parts:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for line_number, line in enumerate(text.splitlines(), start=1):
            if platform_id_pattern.search(line):
                findings.append({"path": relative, "line": line_number, "kind": "platform_id_shape"})
            if token_shape_pattern.search(line):
                findings.append({"path": relative, "line": line_number, "kind": "token_shape"})
            for term in local_terms:
                if term in line:
                    findings.append(
                        {
                            "path": relative,
                            "line": line_number,
                            "kind": "local_private_denylist",
                            "term_hash": hashlib.sha256(term.encode("utf-8")).hexdigest()[:16],
                        }
                    )
    passed = not findings
    return CheckResult(
        name="public_payload_leak_scan",
        status=_status(passed),
        command=["git ls-files", "local private denylist scan if .planning/private_payload_denylist.txt exists"],
        returncode=0,
        summary={
            "tracked_file_count": len(_tracked_files()),
            "local_private_denylist_loaded": bool(local_terms),
            "finding_count": len(findings),
            "findings": findings[:20],
        },
    )


def _git_porcelain() -> list[str]:
    proc = _run(["git", "status", "--porcelain", "--untracked-files=all"])
    if proc.returncode != 0:
        return ["!! git status failed"]
    return [line for line in proc.stdout.splitlines() if line.strip()]


def _visible_untracked() -> list[str]:
    proc = _run(["git", "ls-files", "--others", "--exclude-standard"])
    if proc.returncode != 0:
        return ["git ls-files failed"]
    return [line for line in proc.stdout.splitlines() if line.strip()]


def _git_hygiene_from_lists(porcelain: list[str], visible_untracked: list[str]) -> dict[str, Any]:
    private_live = [path for path in visible_untracked if "live" in path.lower() or "discord" in path.lower()]
    return {
        "git_dirty": bool(porcelain),
        "dirty_entry_count": len(porcelain),
        "visible_untracked_count": len(visible_untracked),
        "untracked_private_files_count": len(private_live),
        "untracked_private_files_policy": "blocked_if_visible",
        "private_live_untracked_visible": bool(private_live),
    }


def _check_git_hygiene() -> CheckResult:
    porcelain = _git_porcelain()
    visible_untracked = _visible_untracked()
    summary = _git_hygiene_from_lists(porcelain, visible_untracked)
    passed = not summary["git_dirty"] and summary["untracked_private_files_count"] == 0
    return CheckResult(
        name="git_hygiene",
        status=_status(passed),
        command=["git status --porcelain", "git ls-files --others --exclude-standard"],
        returncode=0,
        summary=summary,
    )


def _report(checks: list[CheckResult], *, ignore_git_dirty_for_dev: bool) -> dict[str, Any]:
    check_dicts = [
        {
            "name": check.name,
            "status": check.status,
            "returncode": check.returncode,
            "summary": check.summary,
        }
        for check in checks
    ]
    git_check = next((check for check in checks if check.name == "git_hygiene"), None)
    non_git_failures = [check.name for check in checks if check.name != "git_hygiene" and check.status != "pass"]
    git_pass = git_check is not None and git_check.status == "pass"
    release_allowed = not non_git_failures and git_pass
    checklist_passed = release_allowed or (ignore_git_dirty_for_dev and not non_git_failures)
    return {
        "schema": "brainstack.memory_kernel_release_checklist.v1",
        "status": "pass" if checklist_passed else "fail",
        "release_allowed": release_allowed,
        "ignore_git_dirty_for_dev": ignore_git_dirty_for_dev,
        "failed_checks": [check.name for check in checks if check.status != "pass"],
        "non_git_failures": non_git_failures,
        "checks": check_dicts,
    }


def run_checklist(
    *,
    ignore_git_dirty_for_dev: bool = False,
    release_claim_contract: Path = DEFAULT_RELEASE_CLAIM_CONTRACT,
    release_notes: Path = DEFAULT_RELEASE_NOTES,
) -> dict[str, Any]:
    with tempfile.TemporaryDirectory(prefix="brainstack-release-checklist-") as temp:
        tmp = Path(temp)
        checks = [
            _check_release_claim_contract(release_claim_contract, release_notes),
            _check_tier2_unbreakable_operation(tmp),
            _check_phase249_ralph_gate(tmp),
            _check_public_corpus(tmp),
            _check_evidence_trace(tmp),
            _check_packet_budget(tmp),
            _check_active_packet_budget(tmp),
            _check_packet_budget_soak(tmp),
            _check_write_path(tmp),
            _check_graph_conflict_lifecycle(tmp),
            _check_public_fixtures(),
            _check_public_payload_leaks(),
            _check_git_hygiene(),
        ]
    return _report(checks, ignore_git_dirty_for_dev=ignore_git_dirty_for_dev)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path)
    parser.add_argument(
        "--ignore-git-dirty-for-dev",
        action="store_true",
        help="Do not fail process solely because current worktree is dirty. Report still marks release_allowed=false.",
    )
    parser.add_argument(
        "--release-claim-contract",
        type=Path,
        default=DEFAULT_RELEASE_CLAIM_CONTRACT,
        help="Machine-readable release claim contract required for release_allowed=true.",
    )
    parser.add_argument(
        "--release-notes",
        type=Path,
        default=DEFAULT_RELEASE_NOTES,
        help="Release notes file validated against the release claim contract.",
    )
    args = parser.parse_args()

    report = run_checklist(
        ignore_git_dirty_for_dev=args.ignore_git_dirty_for_dev,
        release_claim_contract=args.release_claim_contract,
        release_notes=args.release_notes,
    )
    text = json.dumps(report, indent=2, sort_keys=True)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text + "\n", encoding="utf-8")
    print(text)
    return 0 if report["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
