#!/usr/bin/env python3
"""Run Brainstack memory-kernel release checks as one public-safe gate."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
import tomllib
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from brainstack.benchmark_transparency import REQUIRED_BENCHMARK_VARIANTS

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RELEASE_CLAIM_CONTRACT = ROOT / ".planning" / "release" / "RELEASE-CLAIM-CONTRACT.json"
DEFAULT_RELEASE_NOTES = ROOT / ".planning" / "release" / "RELEASE-NOTES.md"
UNBREAKABLE_TARGET = (
    "MINDE HELYZHETBEN BÁRMILYEN ESETBEN AKÁRHOGY KOMIBNÁLVA BÁRMILYEN "
    "HASZNÁLAT KÖZBEN NEM TÖRHET EL SEMMILYEN ESETBEN SEM SOHA SEHHOGY!"
)
REQUIRED_OPERATION_CLASSES = {
    "inputs",
    "state_transitions",
    "error_modes",
    "conflicts",
    "provider_runtime_failures",
    "replay_idempotency",
    "isolation",
    "contamination",
    "budget_pressure",
    "source_runtime_parity",
    "release_note_truthfulness",
    "arbitrary_combinations",
}
GATE_EVASION_PATTERNS = {
    "scope_shrink",
    "definition_drift",
    "evidence_laundering",
    "silent_downgrade",
    "degraded_success",
    "manual_override",
    "release_note_softening",
    "side_issue_parking",
    "mirror_only_fix",
    "test_only_compliance",
    "metric_cherry_pick",
    "sota_claim_split",
    "fail_closed_abuse",
    "temporary_fallback_as_final",
}
RELEASE_NOTE_FORBIDDEN_PATTERNS = {
    "internal_qa_noise": re.compile(
        r"\b(ruff|pytest|docker rebuild|release checklist|installer doctor|smoke test)\b",
        re.IGNORECASE,
    ),
    "negative_self_disqualification": re.compile(
        r"\b(does not claim|not claim|not product[- ]complete|boundary:|not complete|not ready)\b",
        re.IGNORECASE,
    ),
    "non_maintainer_attribution": re.compile(
        r"\b(co-authored-by|authored by|generated by|automation authored|machine authored)\b",
        re.IGNORECASE,
    ),
}
SUPERIORITY_PATTERN = re.compile(
    r"\b(SOTA|superior|superiority|best|world[- ]class|state[- ]of[- ]the[- ]art)\b",
    re.IGNORECASE,
)
DEFAULT_RELEASE_LIVE_CONTAINER = "hermes-bestie-live"
CRASH_REGRESSION_LOG_NEEDLES = {
    '"exit_code": -11',
    "exit_code=-11",
    "SIGSEGV",
    "Segmentation fault",
    "Traceback",
    "ERROR",
    "NameError: name 'prompt'",
    "Expected where",
    "ModuleNotFoundError",
    "gpt-5.2-codex",
}


@dataclass(frozen=True)
class CheckResult:
    name: str
    status: str
    command: list[str]
    returncode: int
    summary: dict[str, Any]


def _run(command: list[str]) -> subprocess.CompletedProcess[str]:
    env = dict(os.environ)
    existing_pythonpath = env.get("PYTHONPATH", "")
    pythonpath_entries = [str(ROOT)]
    if existing_pythonpath:
        pythonpath_entries.append(existing_pythonpath)
    env["PYTHONPATH"] = os.pathsep.join(pythonpath_entries)
    return subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
        env=env,
    )


def _run_host(command: list[str], *, timeout: int = 90) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            command,
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as exc:
        return subprocess.CompletedProcess(
            command,
            124,
            stdout=str(exc.stdout or ""),
            stderr=f"command timed out after {timeout}s",
        )


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _local_coredump_since(started_at: str | None) -> str:
    if not isinstance(started_at, str) or not started_at.strip():
        return ""
    try:
        parsed = datetime.fromisoformat(started_at.replace("Z", "+00:00"))
    except ValueError:
        return ""
    return parsed.astimezone().strftime("%Y-%m-%d %H:%M:%S")


def _count_log_needles(text: str, needles: set[str] = CRASH_REGRESSION_LOG_NEEDLES) -> dict[str, int]:
    return {needle: text.count(needle) for needle in sorted(needles)}


def _count_python_hermes_coredumps(coredumpctl_output: str) -> int:
    count = 0
    for line in coredumpctl_output.splitlines():
        if not re.search(r"python|hermes", line, re.IGNORECASE):
            continue
        if re.search(r"\b(SIGSEGV|SIGABRT|SIGBUS|SIGILL)\b", line):
            count += 1
    return count


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _json_from_stdout(stdout: str) -> dict[str, Any]:
    return json.loads(stdout.strip() or "{}")


def _status(passed: bool) -> str:
    return "pass" if passed else "fail"


def _as_bool(value: Any) -> bool:
    return value is True


def _as_string_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, str) and item.strip()]


def _all_zero_counters(value: Any) -> bool:
    if not isinstance(value, dict):
        return False
    try:
        return all(int(counter or 0) == 0 for counter in value.values())
    except (TypeError, ValueError):
        return False


def _check_release_claim_contract(
    contract_path: Path = DEFAULT_RELEASE_CLAIM_CONTRACT,
    notes_path: Path = DEFAULT_RELEASE_NOTES,
) -> CheckResult:
    issues: list[dict[str, Any]] = []
    command = ["release claim contract", str(contract_path), str(notes_path)]
    contract: dict[str, Any] = {}
    notes_text = ""

    if not contract_path.exists():
        issues.append({"code": "missing_release_claim_contract", "path": str(contract_path)})
    else:
        try:
            contract = _load_json(contract_path)
        except (OSError, json.JSONDecodeError) as exc:
            issues.append(
                {
                    "code": "invalid_release_claim_contract_json",
                    "path": str(contract_path),
                    "error": str(exc),
                }
            )

    if not notes_path.exists():
        issues.append({"code": "missing_release_notes", "path": str(notes_path)})
    else:
        try:
            notes_text = notes_path.read_text(encoding="utf-8")
        except OSError as exc:
            issues.append({"code": "unreadable_release_notes", "path": str(notes_path), "error": str(exc)})

    if contract:
        if contract.get("schema") != "brainstack.release_claim_contract.v1":
            issues.append({"code": "unsupported_contract_schema", "value": contract.get("schema")})
        if contract.get("stable_release_decision") != "allowed":
            issues.append(
                {
                    "code": "stable_release_decision_not_allowed",
                    "value": contract.get("stable_release_decision"),
                }
            )
        if contract.get("unbreakable_target") != UNBREAKABLE_TARGET:
            issues.append({"code": "unbreakable_target_missing_or_mutated"})
        if not isinstance(contract.get("claim_summary"), str) or not contract["claim_summary"].strip():
            issues.append({"code": "claim_summary_missing"})

        proof = contract.get("unbreakable_operation_proof")
        if not isinstance(proof, dict):
            issues.append({"code": "unbreakable_operation_proof_missing"})
            proof = {}
        if proof.get("status") != "pass":
            issues.append({"code": "unbreakable_operation_proof_not_pass", "value": proof.get("status")})
        classes = set(_as_string_list(proof.get("operating_space_classes")))
        missing_classes = sorted(REQUIRED_OPERATION_CLASSES - classes)
        if missing_classes:
            issues.append({"code": "operating_space_classes_missing", "missing": missing_classes})
        required_true = {
            "arbitrary_combination_coverage",
            "structural_forbidden_state_analysis",
            "no_permanent_disable",
            "no_regression",
            "no_feature_removal",
            "no_capability_shutdown",
            "no_dumbing_down",
            "no_permanent_degraded_mode",
        }
        for key in sorted(required_true):
            if not _as_bool(proof.get(key)):
                issues.append({"code": "unbreakable_proof_required_flag_not_true", "field": key})
        if not _as_string_list(proof.get("structurally_impossible_states")):
            issues.append({"code": "structurally_impossible_states_missing"})
        if not _as_string_list(proof.get("temporary_error_guards")):
            issues.append({"code": "temporary_error_guards_missing"})

        gate_evasion = contract.get("gate_evasion")
        if not isinstance(gate_evasion, dict):
            issues.append({"code": "gate_evasion_section_missing"})
            gate_evasion = {}
        if gate_evasion.get("status") != "pass":
            issues.append({"code": "gate_evasion_status_not_pass", "value": gate_evasion.get("status")})
        for pattern in sorted(GATE_EVASION_PATTERNS):
            if gate_evasion.get(pattern) is not False:
                issues.append({"code": "gate_evasion_pattern_not_rejected", "pattern": pattern})

        immutable = contract.get("immutable_principles")
        if not isinstance(immutable, dict):
            issues.append({"code": "immutable_principles_section_missing"})
            immutable = {}
        if immutable.get("status") != "pass":
            issues.append({"code": "immutable_principles_status_not_pass", "value": immutable.get("status")})
        if immutable.get("violations") not in ([], None):
            issues.append({"code": "immutable_principles_violations_present"})

        sota_gate_required = contract.get("sota_gate_required")
        if not isinstance(sota_gate_required, bool):
            issues.append({"code": "sota_gate_requirement_missing"})
            sota_gate_required = False
        if sota_gate_required:
            sota_gate = contract.get("sota_gate")
            if not isinstance(sota_gate, dict) or sota_gate.get("status") != "pass":
                issues.append({"code": "sota_gate_required_but_not_pass"})

        evidence = contract.get("evidence")
        if not isinstance(evidence, list) or not evidence:
            issues.append({"code": "evidence_missing"})
        else:
            passing_evidence_count = 0
            for index, item in enumerate(evidence):
                if not isinstance(item, dict):
                    issues.append({"code": "evidence_item_invalid", "index": index})
                    continue
                if item.get("status") == "pass":
                    passing_evidence_count += 1
                for field in ("name", "kind", "summary"):
                    if not isinstance(item.get(field), str) or not item[field].strip():
                        issues.append({"code": "evidence_item_field_missing", "index": index, "field": field})
            if passing_evidence_count < 3:
                issues.append({"code": "evidence_too_weak", "passing_evidence_count": passing_evidence_count})

    superiority_claim_in_notes = bool(notes_text and SUPERIORITY_PATTERN.search(notes_text))
    if notes_text:
        for name, pattern in RELEASE_NOTE_FORBIDDEN_PATTERNS.items():
            if pattern.search(notes_text):
                issues.append({"code": "release_notes_forbidden_pattern", "pattern": name})
        for term in _private_payload_terms():
            if term in notes_text:
                issues.append(
                    {
                        "code": "release_notes_private_denylist_term",
                        "term_hash": hashlib.sha256(term.encode("utf-8")).hexdigest()[:16],
                    }
                )
        if superiority_claim_in_notes:
            sota_gate = contract.get("sota_gate") if contract else {}
            if not isinstance(sota_gate, dict) or sota_gate.get("status") != "pass":
                issues.append({"code": "superiority_claim_without_sota_gate"})

    passed = not issues
    return CheckResult(
        name="release_claim_contract",
        status=_status(passed),
        command=command,
        returncode=0 if passed else 1,
        summary={
            "contract_path": str(contract_path),
            "release_notes_path": str(notes_path),
            "issue_count": len(issues),
            "issues": issues[:40],
            "required_operation_class_count": len(REQUIRED_OPERATION_CLASSES),
            "gate_evasion_pattern_count": len(GATE_EVASION_PATTERNS),
            "superiority_claim_in_notes": superiority_claim_in_notes,
        },
    )


def _normalize_release_tag(tag: str) -> str:
    value = str(tag or "").strip()
    if value.startswith("refs/tags/"):
        value = value.removeprefix("refs/tags/")
    if value.startswith("v"):
        value = value[1:]
    return value


def _current_head_tags() -> list[str]:
    proc = _run(["git", "tag", "--points-at", "HEAD"])
    if proc.returncode != 0:
        return []
    return [line.strip() for line in proc.stdout.splitlines() if line.strip()]


def _pyproject_version(pyproject_path: Path) -> tuple[str, list[dict[str, Any]]]:
    issues: list[dict[str, Any]] = []
    if not pyproject_path.exists():
        return "", [{"code": "missing_pyproject", "path": str(pyproject_path)}]
    try:
        data = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        return "", [{"code": "invalid_pyproject", "path": str(pyproject_path), "error": str(exc)}]
    project = data.get("project")
    if not isinstance(project, dict):
        issues.append({"code": "missing_project_section", "path": str(pyproject_path)})
        return "", issues
    version = str(project.get("version") or "").strip()
    if not version:
        issues.append({"code": "missing_project_version", "path": str(pyproject_path)})
    return version, issues


def _version_metadata_parity_summary(
    *,
    pyproject_path: Path = ROOT / "pyproject.toml",
    exact_tags: list[str] | None = None,
) -> dict[str, Any]:
    pyproject_version, issues = _pyproject_version(pyproject_path)
    tag_names = list(exact_tags if exact_tags is not None else _current_head_tags())
    release_tags = [tag for tag in tag_names if re.fullmatch(r"v?\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?", tag)]
    tag_versions = sorted({_normalize_release_tag(tag) for tag in release_tags})
    if len(tag_versions) > 1:
        issues.append({"code": "multiple_exact_release_tag_versions", "tag_versions": tag_versions})
    if pyproject_version and tag_versions and pyproject_version not in tag_versions:
        issues.append(
            {
                "code": "version_metadata_mismatch",
                "pyproject_version": pyproject_version,
                "tag_versions": tag_versions,
            }
        )
    parity_scope = "exact_release_tag" if tag_versions else "not_tagged_head"
    status = _status(not issues)
    return {
        "schema": "brainstack.version_metadata_parity.v1",
        "status": status,
        "parity_scope": parity_scope,
        "pyproject_path": str(pyproject_path),
        "pyproject_version": pyproject_version,
        "exact_release_tags": release_tags,
        "exact_release_tag_versions": tag_versions,
        "issue_count": len(issues),
        "issues": issues[:20],
    }


def _check_version_metadata_parity(
    *,
    pyproject_path: Path = ROOT / "pyproject.toml",
    exact_tags: list[str] | None = None,
) -> CheckResult:
    summary = _version_metadata_parity_summary(pyproject_path=pyproject_path, exact_tags=exact_tags)
    passed = summary.get("status") == "pass"
    return CheckResult(
        name="version_metadata_parity",
        status=_status(passed),
        command=["pyproject version", "git tag --points-at HEAD"],
        returncode=0 if passed else 1,
        summary=summary,
    )


def _check_tier2_unbreakable_operation(tmp: Path) -> CheckResult:
    out = tmp / "tier2_unbreakable_operation_audit.json"
    phase_dir = tmp / "tier2_unbreakable_artifacts"
    command = [
        sys.executable,
        "scripts/audit_tier2_unbreakable_operation.py",
        "--phase-dir",
        str(phase_dir),
        "--artifact-prefix",
        "249",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("issue_count") == 0
        and all(value is True for value in (data.get("proof_families") or {}).values())
        and not any(
            value
            for key, value in (data.get("critical_counters") or {}).items()
            if key != "canonical_event_count"
        )
    )
    return CheckResult(
        name="tier2_unbreakable_operation",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "issue_count": data.get("issue_count"),
            "issues": (data.get("issues") or [])[:20],
            "critical_counters": data.get("critical_counters"),
            "proof_families": data.get("proof_families"),
            "canonical_event_count": data.get("canonical_event_count"),
        },
    )


def _check_phase249_ralph_gate(tmp: Path) -> CheckResult:
    out = tmp / "phase249_ralph_gate.json"
    command = [
        sys.executable,
        "scripts/check_phase249_ralph_gate.py",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = proc.returncode == 0 and data.get("status") == "pass" and data.get("issue_count") == 0
    return CheckResult(
        name="phase249_ralph_gate",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "issue_count": data.get("issue_count"),
            "issues": (data.get("issues") or [])[:20],
            "open_item_count": len(data.get("open_items") or []),
            "blocked_item_count": len(data.get("blocked_items") or []),
            "done_allowed": data.get("done_allowed"),
            "stop_allowed": data.get("stop_allowed"),
            "loop_enforcement": data.get("loop_enforcement"),
            "next_action": data.get("next_action"),
        },
    )


def _check_public_corpus(tmp: Path) -> CheckResult:
    out = tmp / "public_corpus_audit.json"
    command = [sys.executable, "scripts/audit_public_memory_kernel_corpus.py", "--out", str(out)]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = proc.returncode == 0 and data.get("status") == "pass" and not data.get("issues")
    return CheckResult(
        name="public_memory_kernel_corpus",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "scenario_count": data.get("scenario_count"),
            "negative_count": data.get("negative_count"),
            "leak_findings_count": len(data.get("leak_findings") or []),
            "issue_count": len(data.get("issues") or []),
        },
    )


def _check_evidence_trace(tmp: Path) -> CheckResult:
    out = tmp / "evidence_trace_audit.json"
    command = [sys.executable, "scripts/audit_evidence_trace_standard.py", "--out", str(out)]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = proc.returncode == 0 and data.get("status") == "pass" and data.get("issue_count") == 0
    return CheckResult(
        name="evidence_trace_standard",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "scenario_count": data.get("scenario_count"),
            "complete_trace_count": data.get("complete_trace_count"),
            "proof_chain_count": data.get("proof_chain_count"),
            "unknown_reason_code_count": data.get("unknown_reason_code_count"),
            "raw_text_issue_count": data.get("raw_text_issue_count"),
            "issue_count": data.get("issue_count"),
        },
    )


def _check_benchmark_transparency(tmp: Path) -> CheckResult:
    out = tmp / "benchmark_transparency.json"
    command = [
        sys.executable,
        "scripts/run_benchmark_transparency.py",
        "--budget-max-candidate-tokens",
        "70",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    variants = data.get("variants") if isinstance(data.get("variants"), dict) else {}
    off = variants.get("packet_budget_off") if isinstance(variants.get("packet_budget_off"), dict) else {}
    shadow = variants.get("packet_budget_shadow") if isinstance(variants.get("packet_budget_shadow"), dict) else {}
    active = variants.get("packet_budget_active") if isinstance(variants.get("packet_budget_active"), dict) else {}
    off_metrics = off.get("metrics") if isinstance(off.get("metrics"), dict) else {}
    active_metrics = active.get("metrics") if isinstance(active.get("metrics"), dict) else {}
    active_budget = active.get("budget_summary") if isinstance(active.get("budget_summary"), dict) else {}
    shadow_budget = shadow.get("budget_summary") if isinstance(shadow.get("budget_summary"), dict) else {}
    schema_issues = data.get("schema_issues") if isinstance(data.get("schema_issues"), list) else []
    off_precision = off_metrics.get("context_precision")
    active_precision = active_metrics.get("context_precision")
    active_recall = active_metrics.get("context_recall")
    active_protected_drops = active.get("protected_truth_drop_attempts")
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("public_safe") is True
        and not schema_issues
        and len(variants) >= len(REQUIRED_BENCHMARK_VARIANTS)
        and isinstance(off_precision, (int, float))
        and isinstance(active_precision, (int, float))
        and active_precision > off_precision
        and active_recall == 1.0
        and active_protected_drops == 0
        and shadow_budget.get("applied_to_output") is False
        and active_budget.get("applied_to_output") is True
    )
    return CheckResult(
        name="benchmark_transparency",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "schema_issue_count": len(schema_issues),
            "variant_count": len(variants),
            "off_context_precision": off_precision,
            "active_context_precision": active_precision,
            "active_context_recall": active_recall,
            "active_protected_truth_drop_attempts": active_protected_drops,
            "shadow_applied_to_output": shadow_budget.get("applied_to_output"),
            "active_applied_to_output": active_budget.get("applied_to_output"),
            "public_safe": data.get("public_safe"),
        },
    )


def _check_packet_budget(tmp: Path) -> CheckResult:
    out = tmp / "packet_budget_live_shadow.json"
    command = [
        sys.executable,
        "scripts/measure_packet_budget_live_shadow_telemetry.py",
        "--sample-count",
        "24",
        "--budget-max-candidate-tokens",
        "120",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = (
        proc.returncode == 0
        and data.get("scenario_count", 0) >= 20
        and data.get("distinct_scenario_family_count", 0) >= 6
        and data.get("output_changed_in_shadow") is False
        and data.get("protected_truth_drop_attempts") == 0
        and bool(data.get("activation_verdict"))
    )
    return CheckResult(
        name="packet_budget_live_shadow",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "scenario_count": data.get("scenario_count"),
            "distinct_scenario_family_count": data.get("distinct_scenario_family_count"),
            "estimated_delta_percent": data.get("estimated_delta_percent"),
            "protected_truth_drop_attempts": data.get("protected_truth_drop_attempts"),
            "output_changed_in_shadow": data.get("output_changed_in_shadow"),
            "fusion_signal_count": data.get("fusion_signal_count"),
            "retrieval_fusion_next_phase_required": data.get("retrieval_fusion_next_phase_required"),
            "activation_verdict": data.get("activation_verdict"),
        },
    )


def _check_active_packet_budget(tmp: Path) -> CheckResult:
    out = tmp / "packet_budget_active_rollout.json"
    command = [
        sys.executable,
        "scripts/measure_packet_budget_active_rollout.py",
        "--sample-count",
        "24",
        "--budget-max-candidate-tokens",
        "120",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = (
        proc.returncode == 0
        and data.get("active_budget_enabled_for_supported_paths") is True
        and data.get("protected_truth_drop_attempts") == 0
        and data.get("budget_decision_trace_present") is True
        and data.get("budget_reason_code_registry_pass") is True
        and data.get("raw_text_in_budget_trace") is False
        and data.get("unsupported_path_fail_closed_count") == 1
    )
    return CheckResult(
        name="packet_budget_active_rollout",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "active_budget_enabled_for_supported_paths": data.get(
                "active_budget_enabled_for_supported_paths"
            ),
            "scenario_count": data.get("scenario_count"),
            "distinct_scenario_family_count": data.get("distinct_scenario_family_count"),
            "candidate_token_delta_percent": data.get("candidate_token_delta_percent"),
            "packet_build_latency_overhead_ms_p95": data.get(
                "packet_build_latency_overhead_ms_p95"
            ),
            "protected_truth_drop_attempts": data.get("protected_truth_drop_attempts"),
            "budget_reason_code_registry_pass": data.get("budget_reason_code_registry_pass"),
            "raw_text_in_budget_trace": data.get("raw_text_in_budget_trace"),
            "unsupported_path_fail_closed_count": data.get("unsupported_path_fail_closed_count"),
        },
    )


def _check_packet_budget_active_default(tmp: Path) -> CheckResult:
    out = tmp / "packet_budget_active_default.json"
    command = [
        sys.executable,
        "scripts/verify_packet_budget_active_default.py",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("active_default") is True
        and data.get("default_off_detected") is False
        and data.get("shadow_only_detected") is False
        and data.get("hidden_fallback_count") == 0
        and data.get("protected_truth_drop_attempts") == 0
        and data.get("raw_text_trace_count") == 0
        and data.get("public_safe") is True
    )
    return CheckResult(
        name="packet_budget_active_default",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "active_default": data.get("active_default"),
            "default_mode_constant": data.get("default_mode_constant"),
            "resolved_default_mode": data.get("resolved_default_mode"),
            "default_off_detected": data.get("default_off_detected"),
            "shadow_only_detected": data.get("shadow_only_detected"),
            "hidden_fallback_count": data.get("hidden_fallback_count"),
            "protected_truth_drop_attempts": data.get("protected_truth_drop_attempts"),
            "raw_text_trace_count": data.get("raw_text_trace_count"),
            "case_count": data.get("case_count"),
            "failing_cases": data.get("failing_cases"),
            "public_safe": data.get("public_safe"),
        },
    )


def _check_adaptive_evidence_kernel(tmp: Path) -> CheckResult:
    out = tmp / "adaptive_evidence_kernel.json"
    command = [
        sys.executable,
        "scripts/verify_adaptive_evidence_kernel.py",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    bad_success = data.get("bad_success_checks") if isinstance(data.get("bad_success_checks"), dict) else {}
    release_gate = data.get("release_gate") if isinstance(data.get("release_gate"), dict) else {}
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("public_safe") is True
        and data.get("active_default") is True
        and data.get("protected_truth_drops") == 0
        and data.get("tank_false_negative_misses") == 0
        and bad_success.get("status") == "pass"
        and release_gate.get("release_allowed") is True
    )
    return CheckResult(
        name="adaptive_evidence_kernel",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "public_safe": data.get("public_safe"),
            "active_default": data.get("active_default"),
            "protected_truth_drops": data.get("protected_truth_drops"),
            "tank_false_negative_misses": data.get("tank_false_negative_misses"),
            "bad_success_status": bad_success.get("status"),
            "release_allowed": release_gate.get("release_allowed"),
            "runtime_case_count": len(data.get("runtime_cases") or []),
        },
    )


def _check_adaptive_evidence_performance_completion(tmp: Path) -> CheckResult:
    source_hermes = os.environ.get("BRAINSTACK_RELEASE_HERMES_SOURCE", "").strip()
    checks: list[dict[str, Any]] = []

    def run_named(name: str, command: list[str], out: Path) -> dict[str, Any]:
        proc = _run(command)
        data = _load_json(out) if out.exists() else {}
        return {
            "name": name,
            "returncode": proc.returncode,
            "status": data.get("status"),
            "public_safe": data.get("public_safe"),
            "summary": data.get("summary") if isinstance(data.get("summary"), dict) else {},
        }

    if source_hermes:
        fresh_out = tmp / "fresh_hermes_brainstack_install.json"
        checks.append(
            run_named(
                "fresh_hermes_install",
                [
                    sys.executable,
                    "scripts/verify_fresh_hermes_brainstack_install.py",
                    "--source-hermes",
                    source_hermes,
                    "--out",
                    str(fresh_out),
                ],
                fresh_out,
            )
        )
    else:
        checks.append(
            {
                "name": "fresh_hermes_install",
                "returncode": 2,
                "status": "fail",
                "public_safe": True,
                "summary": {"missing_env": "BRAINSTACK_RELEASE_HERMES_SOURCE"},
            }
        )

    commands = [
        (
            "performance_dashboard",
            [sys.executable, "scripts/measure_adaptive_evidence_performance.py", "--iterations", "5"],
            tmp / "adaptive_evidence_performance.json",
        ),
        ("fts5_fast_path", [sys.executable, "scripts/verify_fts5_fast_path.py"], tmp / "fts5_fast_path.json"),
        (
            "corpus_semantic_filtering",
            [sys.executable, "scripts/verify_corpus_semantic_filtering.py"],
            tmp / "corpus_semantic_filtering.json",
        ),
        ("trace_tiering", [sys.executable, "scripts/verify_trace_tiering.py"], tmp / "trace_tiering.json"),
        (
            "persistent_bloat_policy",
            [sys.executable, "scripts/verify_persistent_bloat_policy.py"],
            tmp / "persistent_bloat_policy.json",
        ),
    ]
    for name, base_command, out in commands:
        command = [*base_command, "--out", str(out)]
        checks.append(run_named(name, command, out))

    failed = [check["name"] for check in checks if check.get("returncode") != 0 or check.get("status") != "pass"]
    public_safe = all(check.get("public_safe") is not False for check in checks)
    passed = not failed and public_safe
    return CheckResult(
        name="adaptive_evidence_performance_completion",
        status=_status(passed),
        command=["M008 performance completion verifier bundle"],
        returncode=0 if passed else 1,
        summary={
            "status": "pass" if passed else "fail",
            "failed": failed,
            "public_safe": public_safe,
            "fresh_hermes_source_configured": bool(source_hermes),
            "check_count": len(checks),
            "checks": checks,
        },
    )


def _check_packet_budget_soak(tmp: Path) -> CheckResult:
    out = tmp / "packet_budget_soak.json"
    command = [
        sys.executable,
        "scripts/run_packet_budget_soak.py",
        "--sample-count",
        "100",
        "--budget-max-candidate-tokens",
        "120",
        "--out",
        str(out),
    ]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("scenario_count", 0) >= 100
        and data.get("scenario_family_count", 0) >= 10
        and data.get("protected_truth_drop_attempts") == 0
        and data.get("selected_evidence_fingerprint_mismatch_count") == 0
        and data.get("trace_complete_count") == data.get("scenario_count")
        and data.get("soak_artifact_leak_findings") == 0
        and data.get("failure_bundle_count") == 0
        and data.get("retrieval_fusion_next_phase_required") is False
    )
    return CheckResult(
        name="packet_budget_soak",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "scenario_count": data.get("scenario_count"),
            "scenario_family_count": data.get("scenario_family_count"),
            "candidate_token_delta_percent": data.get("candidate_token_delta_percent"),
            "protected_truth_drop_attempts": data.get("protected_truth_drop_attempts"),
            "selected_evidence_fingerprint_mismatch_count": data.get(
                "selected_evidence_fingerprint_mismatch_count"
            ),
            "trace_complete_count": data.get("trace_complete_count"),
            "soak_artifact_leak_findings": data.get("soak_artifact_leak_findings"),
            "failure_bundle_count": data.get("failure_bundle_count"),
            "retrieval_fusion_next_phase_required": data.get(
                "retrieval_fusion_next_phase_required"
            ),
        },
    )


def _check_write_path(tmp: Path) -> CheckResult:
    out = tmp / "write_path_closure_audit.json"
    command = [sys.executable, "scripts/brainstack_write_path_closure_audit.py", "--json-out", str(out)]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = proc.returncode == 0 and data.get("hard_failure_count") == 0
    return CheckResult(
        name="write_path_closure",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "callsite_count": data.get("callsite_count"),
            "hard_failure_count": data.get("hard_failure_count"),
            "by_class": data.get("by_class", {}),
        },
    )


def _check_graph_conflict_lifecycle(tmp: Path) -> CheckResult:
    out = tmp / "graph_conflict_lifecycle_audit.json"
    command = [sys.executable, "scripts/audit_graph_conflict_lifecycle.py", "--out", str(out)]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("issue_count") == 0
        and data.get("release_blocked_before_resolution") is True
        and data.get("open_conflict_count_after_resolution") == 0
        and data.get("resolution_ledger_count") == 1
    )
    return CheckResult(
        name="graph_conflict_lifecycle",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "issue_count": data.get("issue_count"),
            "release_blocked_before_resolution": data.get("release_blocked_before_resolution"),
            "open_conflict_count_after_resolution": data.get("open_conflict_count_after_resolution"),
            "resolution_ledger_count": data.get("resolution_ledger_count"),
        },
    )


def _check_public_fixtures() -> CheckResult:
    command = [sys.executable, "scripts/run_public_memory_kernel_fixtures.py", "--contract-only"]
    proc = _run(command)
    data = _json_from_stdout(proc.stdout) if proc.stdout.strip().startswith("{") else {}
    passed = proc.returncode == 0 and data.get("negative") == "pass" and data.get("run") == "pass"
    return CheckResult(
        name="public_fixture_runner",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={"negative": data.get("negative"), "run": data.get("run")},
    )


def _check_projection_semantics_runtime_parity(tmp: Path) -> CheckResult:
    out = tmp / "projection_semantics_runtime_parity.json"
    command = [sys.executable, "scripts/verify_projection_semantics_runtime_parity.py", "--out", str(out)]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    counters = data.get("critical_counters") if isinstance(data.get("critical_counters"), dict) else {}
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("inspect_verdict") == "pass"
        and data.get("doctor_status") == "active"
        and data.get("conformance_status") == "pass"
        and data.get("public_safe") is True
        and data.get("unsafe_selected_event_ids") == []
        and counters.get("packet_authority_critical_dropped") == 0
    )
    return CheckResult(
        name="projection_semantics_runtime_parity",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "inspect_verdict": data.get("inspect_verdict"),
            "doctor_status": data.get("doctor_status"),
            "conformance_status": data.get("conformance_status"),
            "event_count": data.get("event_count"),
            "selected_event_ids": data.get("selected_event_ids"),
            "unsafe_selected_event_ids": data.get("unsafe_selected_event_ids"),
            "packet_authority_critical_dropped": counters.get("packet_authority_critical_dropped"),
            "public_safe": data.get("public_safe"),
            "issue_count": len(data.get("issues") or []),
        },
    )


def _check_persistent_bloat_rebuild(tmp: Path) -> CheckResult:
    out = tmp / "persistent_bloat_rebuild.json"
    command = [sys.executable, "scripts/verify_persistent_bloat_rebuild.py", "--out", str(out)]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    proof = data.get("proof") if isinstance(data.get("proof"), dict) else {}
    maintenance = proof.get("maintenance") if isinstance(proof.get("maintenance"), dict) else {}
    preservation = maintenance.get("persistent_bloat_preservation_contract")
    preservation_contract = preservation if isinstance(preservation, dict) else {}
    issues = proof.get("issues") if isinstance(proof.get("issues"), list) else []
    mismatches = proof.get("mismatches") if isinstance(proof.get("mismatches"), list) else []
    critical_counters = proof.get("critical_counters") if isinstance(proof.get("critical_counters"), dict) else {}
    semantic_changes = maintenance.get("semantic_index_changes")
    semantic_index_changes = semantic_changes if isinstance(semantic_changes, list) else []
    semantic_index_truth_mutation_unsafe = any(
        isinstance(change, dict) and change.get("truth_mutation") is not False
        for change in semantic_index_changes
    )
    critical_counters_zero = _all_zero_counters(critical_counters)
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("public_safe") is True
        and proof.get("status") == "pass"
        and proof.get("public_safe") is True
        and issues == []
        and mismatches == []
        and critical_counters_zero
        and maintenance.get("persistent_bloat_apply_status") == "rejected"
        and preservation_contract.get("truth_mutation") is False
        and preservation_contract.get("raw_history_mutation") is False
        and not semantic_index_truth_mutation_unsafe
    )
    return CheckResult(
        name="persistent_bloat_rebuild",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "proof_status": proof.get("status"),
            "public_safe": data.get("public_safe"),
            "proof_public_safe": proof.get("public_safe"),
            "issue_count": len(issues),
            "mismatch_count": len(mismatches),
            "persistent_bloat_apply_status": maintenance.get("persistent_bloat_apply_status"),
            "persistent_bloat_no_op_reasons": list(maintenance.get("persistent_bloat_no_op_reasons") or [])[:8],
            "preservation_contract": {
                "truth_mutation": preservation_contract.get("truth_mutation"),
                "raw_history_mutation": preservation_contract.get("raw_history_mutation"),
                "preserves": list(preservation_contract.get("preserves") or [])[:8],
            },
            "semantic_index_apply_status": maintenance.get("semantic_index_apply_status"),
            "semantic_index_change_count": len(semantic_index_changes),
            "semantic_index_truth_mutation_unsafe": semantic_index_truth_mutation_unsafe,
            "critical_counters": dict(critical_counters),
            "critical_counters_zero": critical_counters_zero,
        },
    )


def _check_tier2_extraction_quality(tmp: Path) -> CheckResult:
    out = tmp / "tier2_extraction_quality.json"
    command = [sys.executable, "scripts/verify_tier2_extraction_quality.py", "--out", str(out)]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    metrics = data.get("metrics") if isinstance(data.get("metrics"), dict) else {}
    harmful_counters = data.get("harmful_counters") if isinstance(data.get("harmful_counters"), dict) else {}
    bloat_impact = data.get("bloat_impact") if isinstance(data.get("bloat_impact"), dict) else {}
    failure_bundles = data.get("failure_bundles") if isinstance(data.get("failure_bundles"), dict) else {}
    unresolved_bundles = failure_bundles.get("unresolved") if isinstance(failure_bundles.get("unresolved"), list) else []
    resolved_bundles = failure_bundles.get("resolved") if isinstance(failure_bundles.get("resolved"), list) else []
    donor_drift = data.get("donor_drift") if isinstance(data.get("donor_drift"), dict) else {}
    quality_class_passes = data.get("quality_class_passes") if isinstance(data.get("quality_class_passes"), dict) else {}
    metrics_all_one = bool(metrics) and all(float(value or 0) == 1.0 for value in metrics.values())
    harmful_zero = _all_zero_counters(harmful_counters)
    public_safe = data.get("public_safe") is True
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and public_safe
        and harmful_zero
        and bloat_impact.get("status") == "pass"
        and donor_drift.get("status") == "pass"
        and metrics_all_one
        and bool(quality_class_passes)
        and all(value is True for value in quality_class_passes.values())
        and unresolved_bundles == []
    )
    return CheckResult(
        name="tier2_extraction_quality",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "public_safe": public_safe,
            "case_count": data.get("case_count"),
            "metrics": dict(metrics),
            "metrics_all_one": metrics_all_one,
            "quality_class_passes": dict(quality_class_passes),
            "harmful_counters": dict(harmful_counters),
            "harmful_counters_zero": harmful_zero,
            "bloat_impact": dict(bloat_impact),
            "donor_drift": dict(donor_drift),
            "resolved_failure_bundle_count": len(resolved_bundles),
            "unresolved_failure_bundle_count": len(unresolved_bundles),
            "claim_boundary": data.get("claim_boundary"),
        },
    )


def _check_hermes_proactive_runtime_parity(tmp: Path) -> CheckResult:
    out = tmp / "hermes_proactive_runtime_parity.json"
    command = [sys.executable, "scripts/verify_hermes_proactive_runtime_parity.py", "--out", str(out)]
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    scenario_statuses = data.get("scenario_statuses") if isinstance(data.get("scenario_statuses"), dict) else {}
    payload_files = data.get("payload_files") if isinstance(data.get("payload_files"), dict) else {}
    expected_statuses = {
        "idle": "idle",
        "active": "active",
        "paused": "paused",
        "dry_run": "observed",
        "killed": "killed",
        "malformed": "degraded",
    }
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("issues") == []
        and data.get("public_safe") is True
        and data.get("zero_runtime_side_effects") is True
        and scenario_statuses == expected_statuses
        and payload_files.get("status") == "present"
        and payload_files.get("missing") == []
    )
    return CheckResult(
        name="hermes_proactive_runtime_parity",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "issue_count": len(data.get("issues") or []),
            "scenario_statuses": scenario_statuses,
            "payload_files_status": payload_files.get("status"),
            "payload_missing_count": len(payload_files.get("missing") or []),
            "public_safe": data.get("public_safe"),
            "zero_runtime_side_effects": data.get("zero_runtime_side_effects"),
        },
    )


def _check_behavior_card_delivery(tmp: Path) -> CheckResult:
    out = tmp / "behavior_card_delivery.json"
    command = [sys.executable, "scripts/verify_behavior_card_delivery.py", "--out", str(out)]
    source_hermes = os.environ.get("BRAINSTACK_RELEASE_HERMES_SOURCE", "").strip()
    if source_hermes:
        command.extend(["--hermes-source", source_hermes])
    proc = _run(command)
    data = _load_json(out) if out.exists() else {}
    legacy_suppression = data.get("legacy_profile_source_suppression")
    legacy_suppression = legacy_suppression if isinstance(legacy_suppression, Mapping) else {}
    size_warning = data.get("active_card_size_warning")
    size_warning = size_warning if isinstance(size_warning, Mapping) else {}
    passed = (
        proc.returncode == 0
        and data.get("status") == "pass"
        and data.get("issues") == []
        and (data.get("session_start") or {}).get("delivery_status") == "delivered_full"
        and (data.get("post_compression") or {}).get("delivery_status") == "delivered_full"
        and (data.get("inspect") or {}).get("active_rule_count") == 25
        and (data.get("durable_behavior_rows") or {}).get("behavior_contracts") == 0
        and (data.get("durable_behavior_rows") or {}).get("compiled_behavior_policies") == 0
        and legacy_suppression.get("suppressed_sources_rendered") == 0
        and legacy_suppression.get("non_behavior_profile_rendered") is True
        and size_warning.get("status") == "warn"
        and size_warning.get("should_warn_user") is True
        and size_warning.get("ack_stable_key") == "brainstack.active_preference_card_size_warning_ack"
    )
    return CheckResult(
        name="behavior_card_delivery",
        status=_status(passed),
        command=command,
        returncode=proc.returncode,
        summary={
            "status": data.get("status"),
            "issue_count": len(data.get("issues") or []),
            "session_start": data.get("session_start"),
            "post_compression": data.get("post_compression"),
            "inspect": data.get("inspect"),
            "durable_behavior_rows": data.get("durable_behavior_rows"),
            "legacy_profile_source_suppression": legacy_suppression,
            "active_card_size_warning": size_warning,
        },
    )


def _live_crash_regression_summary(
    *,
    container_name: str,
    container_id: str | None,
    container_state: dict[str, Any],
    coredumpctl_available: bool,
    coredump_count_since_container_start: int | None,
    coredump_count_after_probe: int | None,
    log_hit_counts: dict[str, int],
    terminal_smoke_ok: bool,
    venv_import_smoke_ok: bool,
    chroma_exception_probe_ok: bool,
    brainstack_model_tool_surface_ok: bool,
    brainstack_model_tool_bytes: dict[str, int] | None = None,
    brainstack_model_tool_surface_issues: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    issues: list[dict[str, Any]] = []
    health = container_state.get("health")
    restart_count = _safe_int(container_state.get("restart_count"), -1)
    exit_code = _safe_int(container_state.get("exit_code"), -1)

    if not container_id:
        issues.append({"code": "live_container_id_missing", "container": container_name})
    if container_state.get("status") != "running":
        issues.append({"code": "live_container_not_running", "status": container_state.get("status")})
    if health != "healthy":
        issues.append({"code": "live_container_not_healthy", "health": health})
    if restart_count != 0:
        issues.append({"code": "live_container_restarted", "restart_count": restart_count})
    if container_state.get("oom_killed") is True:
        issues.append({"code": "live_container_oom_killed"})
    if exit_code not in (0, None):
        issues.append({"code": "live_container_exit_code_nonzero", "exit_code": exit_code})

    nonzero_log_hits = {key: value for key, value in log_hit_counts.items() if _safe_int(value) != 0}
    if nonzero_log_hits:
        issues.append({"code": "live_logs_crash_markers_present", "counts": nonzero_log_hits})

    if not coredumpctl_available:
        issues.append({"code": "coredumpctl_unavailable"})
    if coredump_count_since_container_start is None:
        issues.append({"code": "coredump_count_since_container_start_missing"})
    elif coredump_count_since_container_start != 0:
        issues.append(
            {
                "code": "python_hermes_coredumps_since_container_start",
                "count": coredump_count_since_container_start,
            }
        )
    if coredump_count_after_probe is None:
        issues.append({"code": "coredump_count_after_probe_missing"})
    elif coredump_count_after_probe != 0:
        issues.append({"code": "python_hermes_coredumps_after_probe", "count": coredump_count_after_probe})

    if not terminal_smoke_ok:
        issues.append({"code": "terminal_smoke_failed"})
    if not venv_import_smoke_ok:
        issues.append({"code": "venv_import_smoke_failed"})
    if not chroma_exception_probe_ok:
        issues.append({"code": "chroma_exception_probe_failed"})
    if not brainstack_model_tool_surface_ok:
        issues.append(
            {
                "code": "brainstack_model_tool_surface_unbounded",
                "tool_bytes": dict(brainstack_model_tool_bytes or {}),
                "surface_issues": list(brainstack_model_tool_surface_issues or []),
            }
        )

    passed = not issues
    return {
        "status": "pass" if passed else "fail",
        "container": container_name,
        "container_id_present": bool(container_id),
        "container_status": container_state.get("status"),
        "container_health": health,
        "container_started_at": container_state.get("started_at"),
        "restart_count": restart_count,
        "oom_killed": container_state.get("oom_killed"),
        "exit_code": exit_code,
        "log_hit_counts": dict(sorted(log_hit_counts.items())),
        "logs_crash_markers_zero": not nonzero_log_hits,
        "coredumpctl_available": coredumpctl_available,
        "coredump_count_since_container_start": coredump_count_since_container_start,
        "coredump_count_after_probe": coredump_count_after_probe,
        "terminal_smoke_ok": terminal_smoke_ok,
        "venv_import_smoke_ok": venv_import_smoke_ok,
        "chroma_exception_probe_ok": chroma_exception_probe_ok,
        "brainstack_model_tool_surface_ok": brainstack_model_tool_surface_ok,
        "brainstack_model_tool_bytes": dict(brainstack_model_tool_bytes or {}),
        "brainstack_model_tool_surface_issues": list(brainstack_model_tool_surface_issues or []),
        "public_safe": True,
        "issue_count": len(issues),
        "issues": issues,
    }


def _container_state_from_inspect_output(stdout: str) -> tuple[dict[str, Any], str | None]:
    lines = stdout.splitlines()
    if len(lines) < 3:
        return {}, None
    try:
        raw_state = json.loads(lines[0])
    except json.JSONDecodeError:
        raw_state = {}
    health = raw_state.get("Health") if isinstance(raw_state.get("Health"), dict) else {}
    return (
        {
            "status": raw_state.get("Status"),
            "health": health.get("Status"),
            "started_at": raw_state.get("StartedAt"),
            "oom_killed": raw_state.get("OOMKilled"),
            "exit_code": raw_state.get("ExitCode"),
            "restart_count": _safe_int(lines[1], -1),
        },
        lines[2].strip() or None,
    )


def _check_live_crash_regression_guard(tmp: Path) -> CheckResult:
    container = os.environ.get("BRAINSTACK_RELEASE_LIVE_CONTAINER", DEFAULT_RELEASE_LIVE_CONTAINER).strip()
    command = ["live crash regression guard", container]
    inspect_proc = _run_host(
        [
            "docker",
            "inspect",
            container,
            "--format",
            "{{json .State}}\n{{.RestartCount}}\n{{.Id}}",
        ],
        timeout=30,
    )
    if inspect_proc.returncode != 0:
        summary = _live_crash_regression_summary(
            container_name=container,
            container_id=None,
            container_state={},
            coredumpctl_available=False,
            coredump_count_since_container_start=None,
            coredump_count_after_probe=None,
            log_hit_counts={needle: 0 for needle in CRASH_REGRESSION_LOG_NEEDLES},
            terminal_smoke_ok=False,
            venv_import_smoke_ok=False,
            chroma_exception_probe_ok=False,
            brainstack_model_tool_surface_ok=False,
            brainstack_model_tool_bytes={},
            brainstack_model_tool_surface_issues=[{"code": "docker_inspect_failed"}],
        )
        summary["issues"].append({"code": "docker_inspect_failed", "returncode": inspect_proc.returncode})
        summary["issue_count"] = len(summary["issues"])
        summary["status"] = "fail"
        return CheckResult(
            name="live_crash_regression_guard",
            status="fail",
            command=command,
            returncode=inspect_proc.returncode,
            summary=summary,
        )

    container_state, container_id = _container_state_from_inspect_output(inspect_proc.stdout)
    started_at = str(container_state.get("started_at") or "")
    since = _local_coredump_since(started_at)

    logs_proc = _run_host(["docker", "logs", "--since", started_at, container], timeout=60)
    log_text = (logs_proc.stdout or "") + "\n" + (logs_proc.stderr or "") if logs_proc.returncode == 0 else ""
    log_hit_counts = _count_log_needles(log_text)

    coredumpctl_available = True
    coredump_count_since_container_start: int | None = None
    coredump_count_after_probe: int | None = None
    coredump_command = ["coredumpctl", "--no-pager", "list", "--since", since] if since else []
    if not coredump_command:
        coredumpctl_available = False
    else:
        coredump_proc = _run_host(coredump_command, timeout=30)
        coredumpctl_available = coredump_proc.returncode in (0, 1)
        if coredumpctl_available:
            coredump_count_since_container_start = _count_python_hermes_coredumps(coredump_proc.stdout)

    terminal_proc = _run_host(["docker", "exec", "-i", container, "/bin/sh", "-lc", "echo terminal_smoke_ok"], timeout=30)
    terminal_smoke_ok = terminal_proc.returncode == 0 and "terminal_smoke_ok" in terminal_proc.stdout

    import_script = (
        "import yaml, chromadb\n"
        "from brainstack import BrainstackMemoryProvider\n"
        "print('python_imports_ok')\n"
    )
    import_proc = _run_host(
        ["docker", "exec", "-i", container, "/opt/hermes/.venv/bin/python", "-c", import_script],
        timeout=60,
    )
    venv_import_smoke_ok = import_proc.returncode == 0 and "python_imports_ok" in import_proc.stdout

    probe_root = f"/tmp/brainstack_release_crash_guard_{os.getpid()}"
    chroma_probe_script = f"""
from pathlib import Path
import shutil
from brainstack.db import BrainstackStore
root = Path({probe_root!r})
shutil.rmtree(root, ignore_errors=True)
store = BrainstackStore(str(root / 'brainstack.db'), graph_backend='none', corpus_backend='chroma', corpus_db_path=str(root / 'brainstack.chroma'))
store.open()
try:
    receipt = store.ingest_corpus_source({{
        'source_adapter': 'release_crash_guard',
        'source_id': 'release:crash-guard',
        'stable_key': 'release:crash-guard',
        'title': 'Release Crash Guard',
        'doc_kind': 'diagnostic',
        'source_uri': 'release://crash-guard',
        'content': 'Release crash guard Chroma ingest probe.',
        'metadata': {{'principal_scope_key': 'release:crash-guard'}},
    }})
    print('chroma_probe_ingest_status', receipt.get('status'))
    raise RuntimeError('intentional_release_crash_guard_exception_after_chroma_ingest')
finally:
    store.close()
    shutil.rmtree(root, ignore_errors=True)
"""
    chroma_proc = _run_host(
        [
            "docker",
            "exec",
            "-i",
            "-u",
            "hermes",
            container,
            "/opt/hermes/.venv/bin/python",
            "-c",
            chroma_probe_script,
        ],
        timeout=90,
    )
    chroma_combined_output = f"{chroma_proc.stdout}\n{chroma_proc.stderr}"
    chroma_exception_probe_ok = (
        chroma_proc.returncode == 1
        and "intentional_release_crash_guard_exception_after_chroma_ingest" in chroma_combined_output
    )

    brainstack_model_tool_bytes: dict[str, int] = {}
    brainstack_model_tool_surface_issues: list[dict[str, Any]] = []
    brainstack_model_tool_surface_ok = False
    brainstack_tool_surface_script = r'''
import json
import tempfile
from pathlib import Path
from brainstack import BrainstackMemoryProvider
root = Path(tempfile.mkdtemp(prefix="brainstack-release-tool-surface-"))
provider = BrainstackMemoryProvider({
    "db_path": str(root / "brainstack.sqlite3"),
    "graph_backend": "sqlite",
    "corpus_backend": "sqlite",
})
try:
    provider.initialize(
        "release-tool-surface",
        platform="release",
        user_id="release-user",
        agent_identity="release-agent",
        agent_workspace="release-workspace",
    )
    checks = {
        "brainstack_stats": ({"strict": True}, 6000),
        "brainstack_latency_status": ({}, 4000),
        "brainstack_proactive_status": ({}, 3000),
    }
    tool_bytes = {}
    issues = []
    for name, (args, limit) in checks.items():
        raw = provider.handle_tool_call(name, args)
        tool_bytes[name] = len(raw)
        try:
            payload = json.loads(raw)
        except json.JSONDecodeError:
            issues.append({"code": "tool_output_not_json", "tool": name})
            continue
        if tool_bytes[name] > limit:
            issues.append({"code": "tool_output_too_large", "tool": name, "bytes": tool_bytes[name], "limit": limit})
        if payload.get("bounded_model_facing") is not True:
            issues.append({"code": "tool_not_bounded_model_facing", "tool": name})
        rendered = json.dumps(payload, ensure_ascii=False, sort_keys=True)
        if name == "brainstack_stats" and '"report"' in rendered:
            issues.append({"code": "stats_full_report_exposed", "tool": name})
        if "search_files" in rendered and "do_not_call_search_files" not in rendered:
            issues.append({"code": "tool_surface_encourages_file_search", "tool": name})
    print(json.dumps({"tool_bytes": tool_bytes, "issues": issues}, sort_keys=True))
finally:
    provider.shutdown()
'''
    brainstack_tool_surface_proc = _run_host(
        [
            "docker",
            "exec",
            "-i",
            container,
            "/opt/hermes/.venv/bin/python",
            "-c",
            brainstack_tool_surface_script,
        ],
        timeout=60,
    )
    if brainstack_tool_surface_proc.returncode == 0:
        try:
            brainstack_tool_surface_data = json.loads(brainstack_tool_surface_proc.stdout.strip().splitlines()[-1])
        except (IndexError, json.JSONDecodeError):
            brainstack_tool_surface_data = {"issues": [{"code": "tool_surface_probe_output_malformed"}]}
        brainstack_model_tool_bytes = {
            str(name): _safe_int(value, -1)
            for name, value in (brainstack_tool_surface_data.get("tool_bytes") or {}).items()
        }
        raw_issues = brainstack_tool_surface_data.get("issues") or []
        brainstack_model_tool_surface_issues = [dict(issue) for issue in raw_issues if isinstance(issue, Mapping)]
        brainstack_model_tool_surface_ok = not brainstack_model_tool_surface_issues and bool(brainstack_model_tool_bytes)
    else:
        brainstack_model_tool_surface_issues = [
            {"code": "tool_surface_probe_failed", "returncode": brainstack_tool_surface_proc.returncode}
        ]

    if coredump_command and coredumpctl_available:
        coredump_after_proc = _run_host(coredump_command, timeout=30)
        if coredump_after_proc.returncode in (0, 1):
            coredump_count_after_probe = _count_python_hermes_coredumps(coredump_after_proc.stdout)

    summary = _live_crash_regression_summary(
        container_name=container,
        container_id=container_id,
        container_state=container_state,
        coredumpctl_available=coredumpctl_available,
        coredump_count_since_container_start=coredump_count_since_container_start,
        coredump_count_after_probe=coredump_count_after_probe,
        log_hit_counts=log_hit_counts,
        terminal_smoke_ok=terminal_smoke_ok,
        venv_import_smoke_ok=venv_import_smoke_ok,
        chroma_exception_probe_ok=chroma_exception_probe_ok,
        brainstack_model_tool_surface_ok=brainstack_model_tool_surface_ok,
        brainstack_model_tool_bytes=brainstack_model_tool_bytes,
        brainstack_model_tool_surface_issues=brainstack_model_tool_surface_issues,
    )
    if logs_proc.returncode != 0:
        summary["issues"].append({"code": "docker_logs_failed", "returncode": logs_proc.returncode})
    summary["issue_count"] = len(summary["issues"])
    summary["status"] = "pass" if not summary["issues"] else "fail"
    passed = summary["status"] == "pass"
    return CheckResult(
        name="live_crash_regression_guard",
        status=_status(passed),
        command=command,
        returncode=0 if passed else 1,
        summary=summary,
    )


def _tracked_files() -> list[str]:
    proc = _run(["git", "ls-files"])
    if proc.returncode != 0:
        return []
    return [line.strip() for line in proc.stdout.splitlines() if line.strip()]


def _private_payload_terms() -> list[str]:
    denylist_path = ROOT / ".planning" / "private_payload_denylist.txt"
    if not denylist_path.exists():
        return []
    terms: list[str] = []
    for raw in denylist_path.read_text(encoding="utf-8").splitlines():
        term = raw.strip()
        if not term or term.startswith("#"):
            continue
        terms.append(term)
    return terms


def _check_public_payload_leaks() -> CheckResult:
    local_terms = _private_payload_terms()
    platform_id_pattern = re.compile(
        r"(?:user_id|channel_id|thread_id|server_id|guild_id|principal|telegram|discord)[^\\n]{0,80}\\b\\d{12,}\\b",
        re.IGNORECASE,
    )
    token_shape_pattern = re.compile(r"\\b[A-Za-z0-9_-]{20,}\\.[A-Za-z0-9_-]{6,}\\.[A-Za-z0-9_-]{20,}\\b")
    findings: list[dict[str, Any]] = []
    for relative in _tracked_files():
        path = ROOT / relative
        if not path.is_file() or "__pycache__" in path.parts:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for line_number, line in enumerate(text.splitlines(), start=1):
            if platform_id_pattern.search(line):
                findings.append({"path": relative, "line": line_number, "kind": "platform_id_shape"})
            if token_shape_pattern.search(line):
                findings.append({"path": relative, "line": line_number, "kind": "token_shape"})
            for term in local_terms:
                if term in line:
                    findings.append(
                        {
                            "path": relative,
                            "line": line_number,
                            "kind": "local_private_denylist",
                            "term_hash": hashlib.sha256(term.encode("utf-8")).hexdigest()[:16],
                        }
                    )
    passed = not findings
    return CheckResult(
        name="public_payload_leak_scan",
        status=_status(passed),
        command=["git ls-files", "local private denylist scan if .planning/private_payload_denylist.txt exists"],
        returncode=0,
        summary={
            "tracked_file_count": len(_tracked_files()),
            "local_private_denylist_loaded": bool(local_terms),
            "finding_count": len(findings),
            "findings": findings[:20],
        },
    )


def _git_porcelain() -> list[str]:
    proc = _run(["git", "status", "--porcelain", "--untracked-files=all"])
    if proc.returncode != 0:
        return ["!! git status failed"]
    return [line for line in proc.stdout.splitlines() if line.strip()]


def _visible_untracked() -> list[str]:
    proc = _run(["git", "ls-files", "--others", "--exclude-standard"])
    if proc.returncode != 0:
        return ["git ls-files failed"]
    return [line for line in proc.stdout.splitlines() if line.strip()]


def _private_live_untracked_files(visible_untracked: list[str]) -> list[str]:
    private_tokens = {"live", "discord", "bestie"}
    private_files: list[str] = []
    for path in visible_untracked:
        tokens = {token for token in re.split(r"[^a-z0-9]+", path.lower()) if token}
        if tokens & private_tokens:
            private_files.append(path)
    return private_files


def _git_hygiene_from_lists(porcelain: list[str], visible_untracked: list[str]) -> dict[str, Any]:
    private_live = _private_live_untracked_files(visible_untracked)
    return {
        "git_dirty": bool(porcelain),
        "dirty_entry_count": len(porcelain),
        "visible_untracked_count": len(visible_untracked),
        "untracked_private_files_count": len(private_live),
        "untracked_private_files_policy": "blocked_if_visible",
        "private_live_untracked_visible": bool(private_live),
    }


def _check_git_hygiene() -> CheckResult:
    porcelain = _git_porcelain()
    visible_untracked = _visible_untracked()
    summary = _git_hygiene_from_lists(porcelain, visible_untracked)
    passed = not summary["git_dirty"] and summary["untracked_private_files_count"] == 0
    return CheckResult(
        name="git_hygiene",
        status=_status(passed),
        command=["git status --porcelain", "git ls-files --others --exclude-standard"],
        returncode=0,
        summary=summary,
    )


def _report(checks: list[CheckResult], *, ignore_git_dirty_for_dev: bool) -> dict[str, Any]:
    check_dicts = [
        {
            "name": check.name,
            "status": check.status,
            "returncode": check.returncode,
            "summary": check.summary,
        }
        for check in checks
    ]
    git_check = next((check for check in checks if check.name == "git_hygiene"), None)
    non_git_failures = [check.name for check in checks if check.name != "git_hygiene" and check.status != "pass"]
    git_pass = git_check is not None and git_check.status == "pass"
    release_allowed = not non_git_failures and git_pass
    checklist_passed = release_allowed or (ignore_git_dirty_for_dev and not non_git_failures)
    return {
        "schema": "brainstack.memory_kernel_release_checklist.v1",
        "status": "pass" if checklist_passed else "fail",
        "release_allowed": release_allowed,
        "ignore_git_dirty_for_dev": ignore_git_dirty_for_dev,
        "failed_checks": [check.name for check in checks if check.status != "pass"],
        "non_git_failures": non_git_failures,
        "checks": check_dicts,
    }


def run_checklist(
    *,
    ignore_git_dirty_for_dev: bool = False,
    release_claim_contract: Path = DEFAULT_RELEASE_CLAIM_CONTRACT,
    release_notes: Path = DEFAULT_RELEASE_NOTES,
) -> dict[str, Any]:
    with tempfile.TemporaryDirectory(prefix="brainstack-release-checklist-") as temp:
        tmp = Path(temp)
        checks = [
            _check_release_claim_contract(release_claim_contract, release_notes),
            _check_version_metadata_parity(),
            _check_tier2_unbreakable_operation(tmp),
            _check_phase249_ralph_gate(tmp),
            _check_public_corpus(tmp),
            _check_evidence_trace(tmp),
            _check_benchmark_transparency(tmp),
            _check_packet_budget(tmp),
            _check_active_packet_budget(tmp),
            _check_packet_budget_active_default(tmp),
            _check_adaptive_evidence_kernel(tmp),
            _check_adaptive_evidence_performance_completion(tmp),
            _check_packet_budget_soak(tmp),
            _check_write_path(tmp),
            _check_graph_conflict_lifecycle(tmp),
            _check_public_fixtures(),
            _check_projection_semantics_runtime_parity(tmp),
            _check_hermes_proactive_runtime_parity(tmp),
            _check_behavior_card_delivery(tmp),
            _check_live_crash_regression_guard(tmp),
            _check_persistent_bloat_rebuild(tmp),
            _check_tier2_extraction_quality(tmp),
            _check_public_payload_leaks(),
            _check_git_hygiene(),
        ]
    return _report(checks, ignore_git_dirty_for_dev=ignore_git_dirty_for_dev)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path)
    parser.add_argument(
        "--ignore-git-dirty-for-dev",
        action="store_true",
        help="Do not fail process solely because current worktree is dirty. Report still marks release_allowed=false.",
    )
    parser.add_argument(
        "--release-claim-contract",
        type=Path,
        default=DEFAULT_RELEASE_CLAIM_CONTRACT,
        help="Machine-readable release claim contract required for release_allowed=true.",
    )
    parser.add_argument(
        "--release-notes",
        type=Path,
        default=DEFAULT_RELEASE_NOTES,
        help="Release notes file validated against the release claim contract.",
    )
    args = parser.parse_args()

    report = run_checklist(
        ignore_git_dirty_for_dev=args.ignore_git_dirty_for_dev,
        release_claim_contract=args.release_claim_contract,
        release_notes=args.release_notes,
    )
    text = json.dumps(report, indent=2, sort_keys=True)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text + "\n", encoding="utf-8")
    print(text)
    return 0 if report["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
